---
abstract: 'parse SMS Server Tools files'
author:
  - 'Thomas Lenz <tholen@cpan.org>'
build_requires:
  Class::Accessor: '0.31'
  Log::Log4perl: '1'
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: SMS-Server-Tools
provides:
  SMS::Server::Tools:
    file: lib/SMS/Server/Tools.pm
    version: '0.02'
requires:
  Class::Accessor: '0.31'
  Log::Log4perl: '1'
  Test::More: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=SMS-Server-Tools
  license: http://dev.perl.org/licenses/
  repository: http://github.com/tholen/sms-server-tools-perl
version: '0.02'
