---
name: SMS-Server-Tools
version: 0.01
author:
  - 'Thomas Lenz <tholen@cpan.org>'
abstract: parse SMS Server Tools files
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Class::Accessor: 0.31
  Test::More: 0
provides:
  SMS::Server::Tools:
    file: lib/SMS/Server/Tools.pm
    version: 0.01
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
